### ISSUE TITLE
Raspberry Sensehat - HassIO

### ISSUE THREAD

**Issue by phiwa99** [home-assistant/addons-development#17]
Dear all, I know I am talking alone but here is the solution I came with:

```yaml
pypi:
  - >-
    git+https://github.com/RPi-Distro/RTIMULib#egg=rtimulib&subdirectory=Linux/python
apk:
  - gcc
  - g++
  - py3-sensehat
  - i2c-tools-dev
  - python3-dev
  - raspberrypi-dev
  - raspberrypi-libs
```

and it is working! I am going to change the title of the issue as it does not reflect the issue of the problem. The steps to make this work are documented in [this PR](https://github.com/home-assistant/home-assistant.io/pull/15503)

_Originally posted by @denics in https://github.com/home-assistant/addons-development/issues/11#issuecomment-719937824_

This code does not work on my raspberry pi 4 running 2020.12.7

with this code i get an error:
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[Info] Remove old deps
[Info] Install apks for build
[Info] Install pypi modules into deps
Running command git clone -q https://github.com/RPi-Distro/RTIMULib /tmp/pip-install-o_qx4viu/rtimulib
WARNING: You are using pip version 20.1.1; however, version 20.3.3 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
[Info] done
[cmd] /run.sh exited 0
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

Is the pip version part of the hassio virtual environment?
